/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
((E,e)=>{function L(a){if(1===a){d.removeEventListener("onStateChange",L);S();M.forEach(h=>{h()});b.defaultvolume&&d.setVolume(b.volume);a=b.speed;let c,g,f;if(null==(g=(c=d).getVideoData)?0:null==(f=g.call(c))?0:f.isLive)a=1;b.overridespeeds?(l.playbackRate=a,l.defaultPlaybackRate=a):d.setPlaybackRate(a)}}function T(a){1===a&&b.pausevideos&&F.postMessage({message:"pause-video"});1!==a&&3!==a||!b.selectquality||G||z();1===a?m.classList.add("ytp-pause-overlay-hidden"):2===a?setTimeout(()=>
{d.classList.remove("ytp-expand-pause-overlay");m.classList.remove("ytp-pause-overlay-hidden")},1E3):0===a&&(G=!1)}function U(a){if(a.ctrlKey){a.preventDefault();a=a.shiftKey?1:b.speed;if(b.overridespeeds)l.playbackRate=a;else{let c;null==(c=d)||c.setPlaybackRate(a)}r.textContent=a+"x";H()}}function V(){x=u=v=!1;e.body.classList.remove("ytp-contextmenu-hidden")}function W(a){2===a.button&&(b.controlvolumemousebutton||b.controlspeedmousebutton)&&(x=!0,e.body.classList.add("ytp-contextmenu-hidden"))}
function X(a){2===a.button&&(b.controlvolumemousebutton||b.controlspeedmousebutton)&&(x=!1,N?u||v?setTimeout(O,500):e.body.classList.remove("ytp-contextmenu-hidden"):(u||v?(A=!0,setTimeout(O,500)):(A=!1,e.body.classList.remove("ytp-contextmenu-hidden")),u=v=!1))}function Y(a){if(N&&(b.controlvolumemousebutton&&u||b.controlspeedmousebutton&&v))return a.stopPropagation(),a.preventDefault(),u=v=!1;if((b.controlvolumemousebutton||b.controlspeedmousebutton)&&A)return a.preventDefault(),A=!1}function Z(a){if(!d.classList.contains("ytp-settings-shown")&&
!d.classList.contains("ytp-menu-shown"))if(a.ctrlKey&&b.controlspeed&&(b.controlspeedmousebutton&&x||!b.controlspeedmousebutton)){a.preventDefault();try{if(b.overridespeeds){var c=l.playbackRate;if(!b.reversemousewheeldirection&&0<a.deltaY||b.reversemousewheeldirection&&0>a.deltaY)c=parseFloat((c-b.speedvariation).toFixed(2)),0>=c&&(c=b.speedvariation),l.playbackRate=c;else if(!b.reversemousewheeldirection&&0>a.deltaY||b.reversemousewheeldirection&&0<a.deltaY)c=parseFloat((c+b.speedvariation).toFixed(2)),
l.playbackRate=c}else{var g=d.getAvailablePlaybackRates();c=d.getPlaybackRate();var f=g.indexOf(c);(!b.reversemousewheeldirection&&0<a.deltaY||b.reversemousewheeldirection&&0>a.deltaY)&&0<f?(c=g[f-1],d.setPlaybackRate(c)):(!b.reversemousewheeldirection&&0>a.deltaY||b.reversemousewheeldirection&&0<a.deltaY)&&f<g.length-1&&(c=g[f+1],d.setPlaybackRate(c))}v=!0;r.textContent=c+"x";H()}catch(k){}}else if(b.controlvolume&&(b.controlvolumemousebutton&&x||!b.controlvolumemousebutton)){a.preventDefault();
try{var h=d.getVolume();!b.reversemousewheeldirection&&0<a.deltaY||b.reversemousewheeldirection&&0>a.deltaY?(h-=b.volumevariation,0>h&&(h=0)):(h+=b.volumevariation,100<h&&(h=100),d.isMuted()&&d.unMute());u=!0;d.setVolume(h);r.textContent=h;H()}catch(k){}}}function O(){var a=e.querySelector(".ytp-popup.ytp-contextmenu");a&&0<a.getBoundingClientRect().height&&(a.style.display="none");e.body.classList.remove("ytp-contextmenu-hidden")}function z(){var a=d.getAvailableQualityLevels(),c=e.fullscreenElement?
b.qualityembedsfullscreen:b.qualityembeds;if(a.includes(c)){let g,f;null==(f=(g=d).setPlaybackQuality)||f.call(g,c);let h,k;null==(k=(h=d).setPlaybackQualityRange)||k.call(h,c)}else{c=["large","medium","small","tiny"].includes(c)?"auto":a[0];let g,f;null==(f=(g=d).setPlaybackQuality)||f.call(g,c);let h,k;null==(k=(h=d).setPlaybackQualityRange)||k.call(h,c)}}function H(){r.setAttribute("style",I.createScript("display:block!important"));clearTimeout(P);P=setTimeout(()=>{r.setAttribute("style",I.createScript("display:none!important"))},
1500)}function aa(){J.dispatchEvent(new Event("mouseover"));J.dispatchEvent(new Event("mouseout"));y||(y=d.querySelector(".ytp-tooltip:not(.ytp-efyt-tooltip)"));y&&""!==y.style.top&&(B.textContent=this.dataset.tooltip,n.style.display="block",n.style.top=y.style.top,n.style.left=this.parentNode.parentNode.parentNode.offsetLeft+this.offsetLeft+this.offsetWidth/2-n.getBoundingClientRect().width/2+"px")}function ba(){n.style.display="none"}function ca(a,c,g){var f=e.createElement("button"),h=e.createElementNS("http://www.w3.org/2000/svg",
"use"),k=e.createElementNS("http://www.w3.org/2000/svg","svg"),q=e.createElementNS("http://www.w3.org/2000/svg","path");f.className="ytp-button ytp-efyt-button";f.style.display=b.controls.includes(a)?"inline-block":"none";k.setAttributeNS(null,"version","1.1");k.setAttributeNS(null,"viewBox","0 0 36 36");k.setAttributeNS(null,"height","100%");k.setAttributeNS(null,"width","100%");h.setAttribute("class",I.createScript("ytp-svg-shadow"));h.setAttributeNS("http://www.w3.org/1999/xlink","href","#ytp-efyt-"+
a);q.setAttributeNS(null,"id","ytp-efyt-"+a);q.setAttributeNS(null,"d",c);q.setAttributeNS(null,"fill","#fff");g&&q.setAttributeNS(null,"transform",g);k.appendChild(h);k.appendChild(q);f.appendChild(k);f.addEventListener("mouseover",aa);f.addEventListener("mouseout",ba);return f}function S(){J=d.querySelector(".ytp-settings-button");B=e.createElement("span");B.className="ytp-tooltip-text";var a=e.createElement("div");a.appendChild(B);a.className="ytp-tooltip-text-wrapper";n=e.createElement("div");
n.appendChild(a);n.className="ytp-tooltip ytp-efyt-tooltip";n.style.display="none";d.appendChild(n);a=ca("screenshot","M 26.079999,10.02 H 22.878298 L 21.029999,8 h -6.06 l -1.8483,2.02 H 9.9200015 c -1.111,0 -2.02,0.909 -2.02,2.02 v 12.12 c 0,1.111 0.909,2.02 2.02,2.02 H 26.079999 c 1.111,0 2.019999,-0.909 2.019999,-2.02 V 12.04 c 0,-1.111 -0.909,-2.02 -2.019999,-2.02 z m 0,14.14 H 9.9200015 V 12.04 h 4.0904965 l 1.8483,-2.02 h 4.2824 l 1.8483,2.02 h 4.0905 z m -8.08,-11.11 c -2.7876,0 -5.05,2.2624 -5.05,5.05 0,2.7876 2.2624,5.05 5.05,5.05 2.7876,0 5.049999,-2.2624 5.049999,-5.05 0,-2.7876 -2.262399,-5.05 -5.049999,-5.05 z m 0,8.08 c -1.6665,0 -3.03,-1.3635 -3.03,-3.03 0,-1.6665 1.3635,-3.03 3.03,-3.03 1.6665,0 3.03,1.3635 3.03,3.03 0,1.6665 -1.3635,3.03 -3.03,3.03 z");
a.dataset.tooltip=Q.screenshot;a.id="efyt-screenshot";a.addEventListener("click",()=>{if(l){var f=e.createElement("canvas"),h=f.getContext("2d"),k=l.clientWidth,q=l.clientHeight,da=(t=>{var p=Math.floor(t/3600),w=Math.floor(t%3600/60);t=Math.floor(t%3600%60);return(0<p?p+"h":"")+(0<w?(0<p&&10>w?"0":"")+w+"m":0<p&&0===w?"00m":"0m")+(10>t?"0":"")+t+"s"})(parseInt(d.getCurrentTime(),10));f.width=k;f.height=q;h.drawImage(l,0,0,k,q);f.toBlob(t=>{var p=d.getVideoData(),w=p.author.replace(/[\\/:*?"<>|]+/g,
"").replace(/\s+/g," ").trim(),ea=p.title.replace(/[\\/:*?"<>|]+/g,"").replace(/\s+/g," ").trim();p=p.video_id;var C=e.createElement("a");C.href=URL.createObjectURL(t);C.download=`${w} - ${ea} [${p} - ${k}x${q} - ${da}].png`;C.click();URL.revokeObjectURL(C.href)})}});var c=d.querySelector(".ytp-right-controls");c&&c.insertBefore(a,c.firstChild);var g=d.querySelector(".ytp-title-text");g&&d.addEventListener("onStateChange",()=>{E.top.document.title=g.textContent+" - Enhancer for YouTube\u2122"})}function fa(){d.loadPlaylist(D.videos,
D.index,D.start)}var b,R,F,D,M=[],Q={},N=String(navigator.userAgent).includes("Windows"),x=!1,v=!1,u=!1,G,A,P,r,l,d,m,J,y,n,B,I=E.trustedTypes.createPolicy("efyt-trusted-types-policy",{createHTML:a=>a,createScript:a=>a,createScriptURL:a=>a});e.addEventListener("DOMContentLoaded",()=>{var a=e.createElement("style");a.textContent="#efyt-bezel{display:none;background-color:rgba(0,0,0,.5);color:#fff;font-size:175%;border-radius:3px;padding:10px 20px;position:absolute;top:10%;left:50%;transform:translateX(-50%);z-index:19} body.ytp-contextmenu-hidden .ytp-contextmenu{visibility:hidden!important} .ytp-pause-overlay-hidden .ytp-pause-overlay{display:none!important}";
e.head.appendChild(a);r=e.createElement("div");r.id="efyt-bezel"},{once:!0});e.addEventListener("click",()=>{interaction=!0},{once:!0,capture:!0});e.addEventListener("efyt-init",a=>{b=a.detail.prefs;R=a.detail.version;Q=a.detail.messages;F=new BroadcastChannel("efyt-"+R);F.addEventListener("message",c=>{if("pause-video"===c.data.message&&!b.ignorepopupplayer){let g;null==(g=d)||g.pauseVideo()}})},{once:!0});e.addEventListener("efyt-pop-up-player-message",a=>{"load-playlist"===a.detail.message&&(D=
a.detail.playlist,M.push(fa))});e.addEventListener("efyt-preference-changed",a=>{var c=a.detail.name;a=a.detail.value;b[c]=a;if(d)switch(c){case "controls":b.controls=a;d.querySelectorAll(".ytp-efyt-button").forEach(function(g){var f=g.id.split("efyt-")[1];g.style.display=b.controls.includes(f)?"inline-block":"none"});break;case "defaultvolume":b.defaultvolume&&d.setVolume(b.volume);break;case "overridespeeds":b.overridespeeds?(l.playbackRate=b.speed,l.defaultPlaybackRate=b.speed):d.setPlaybackRate(b.speed);
break;case "selectquality":b.selectquality&&(G=!1,z())}});var K;"onfullscreenchange"in e?K="fullscreenchange":"onmozfullscreenchange"in e&&(K="mozfullscreenchange");e.addEventListener(K,a=>{setTimeout(()=>{e.fullscreenElement&&b.selectquality&&b.selectqualityfullscreenon?z():!e.fullscreenElement&&b.selectquality&&b.selectqualityfullscreenoff&&z()},500)});const ha=HTMLVideoElement.prototype.play;HTMLVideoElement.prototype.play=function(){!l&&this.classList.contains("html5-main-video")&&(l=this,l.addEventListener("click",
U));!d&&(d=e.querySelector("#movie_player"))&&(d.appendChild(r),d.addEventListener("onStateChange",L),d.addEventListener("onStateChange",T));!m&&(m=e.querySelector("#player:has(#movie_player)"))&&(m.classList.add("ytp-pause-overlay-hidden"),m.addEventListener("mouseleave",V),m.addEventListener("mousedown",W,!0),m.addEventListener("mouseup",X,!0),m.addEventListener("contextmenu",Y,!0),m.addEventListener("wheel",Z));return b?ha.apply(this,arguments):(setTimeout(()=>{let a;null==(a=l)||a.play()},500),
new Promise((a,c)=>c(new DOMException("NotAllowedError"))))};if(E.MediaSource){const a=MediaSource.isTypeSupported;MediaSource.isTypeSupported=function(){return function(c){return b&&b.blockhfrformats&&/framerate=([4-6]\d|\d{3,})/.test(c)||b&&b.blockwebmformats&&/video\/webm/.test(c)?!1:a(c)}}}})(window,document);