/*
##
##  Enhancer for YouTube™
##  =====================
##
##  Author: Maxime RF <https://www.mrfdev.com>
##
##  This file is protected by copyright laws and international copyright
##  treaties, as well as other intellectual property laws and treaties.
##
##  All rights not expressly granted to you are retained by the author.
##  Read the license.txt file for more details.
##
##  © MRFDEV.com - All Rights Reserved
##
*/
((b,D)=>{function g(){var a={};this.name?a[this.name]=this.value:a[this.id]=this.checked;chrome.storage.local.set(a)}function Ia(){for(var a=[],d=0;d<t.length;d++)t[d].checked&&a.push(t[d].id);chrome.storage.local.set({controls:a})}function p(){chrome.storage.local.set({griditemsperrow:f})}function va(){for(var a={},d=0;d<m.length;d++)a[m[d].name]=m[d].value;chrome.storage.local.set({customcolors:a})}function O(){for(var a="youtube-deep-dark-custom"===b.querySelector('input[name="theme"]:checked').value?
!1:!0,d=0;d<m.length;d++)m[d].disabled=a;P.disabled=a}function wa(){fetch(chrome.runtime.getURL(`_locales/${u}/messages.json`)).then(a=>a.json()).then(a=>{Q=a.locale_dir.message;b.documentElement.lang=u.replace("_","-");b.body.dir=Q;for(var d=A.length-1;0<=d;d--)A[d].textContent=a[A[d].dataset.text].message;for(d=n.length-1;0<=d;d--)n[d].dataset.tooltip=a[n[d].dataset.message].message;b.querySelector("#customcss").setAttribute("placeholder",a.custom_theme_instructions.message);b.querySelector("#customscript").setAttribute("placeholder",
a.custom_script_instructions.message);chrome.storage.local.set({localecode:u,localedir:Q})})}function xa(a){b.body.classList.add("overflow-hidden");E.style.display="block";a.style.display="block";a.scrollTop=0;E.classList.add("in");setTimeout(()=>{b.body.classList.add("modal-open");a.querySelector("button.close-modal").focus()},50)}function Ja(a){b.body.classList.remove("modal-open");setTimeout(()=>{a.style.display="none";E.classList.add("fade");E.classList.remove("in");setTimeout(()=>{E.style.display=
"none";b.body.classList.remove("overflow-hidden");b.querySelector("fieldset.backup button").focus()},300)},300)}function ya(){var a=b.querySelector("main"),d=b.createElement("style");d.textContent=`:root{--main-inset-shadow-top:${a.offsetTop}px;--main-inset-shadow-width:${a.clientWidth}px}`;b.head.appendChild(d)}var u=chrome.i18n.getMessage("locale_code"),Q=chrome.i18n.getMessage("locale_dir"),A=b.querySelectorAll(".i18n"),v=b.querySelector("main"),r=b.querySelector(".tooltip"),E=b.querySelector("#modal-backdrop"),
m=b.querySelectorAll('#customcolors input[type="color"]'),P=b.querySelector("#reset-custom-colors"),n=b.querySelectorAll(".player-control .info"),t,f;chrome.storage.onChanged.addListener((a,d)=>{for(const e in a)void 0!==a[e].newValue&&("darktheme"===e&&a[e].newValue!==b.querySelector("#darktheme").checked?b.querySelector("#darktheme").click():"theme"===e&&a[e].newValue!==b.querySelector('input[name="theme"]:checked').value?(b.querySelector(`input[name="theme"][value="${a[e].newValue}"]`).checked=
!0,b.querySelector("#themevariant").disabled="enhanced-dark"===a[e].newValue?!1:!0,b.querySelector("#vendorthemevariant").disabled="youtube-deep-dark"===a[e].newValue?!1:!0,O()):"customtheme"===e&&(d=b.querySelector("#customtheme"),d.checked!==a[e].newValue&&(d.checked=a[e].newValue),b.querySelector("#customcss").disabled=!d.checked,b.querySelector("#customcss-btn").disabled=!d.checked))});chrome.storage.local.get(D,a=>{if(u===a.localecode){b.documentElement.lang=u.replace("_","-");b.body.dir=Q;for(var d=
A.length-1;0<=d;d--)A[d].textContent=chrome.i18n.getMessage(A[d].dataset.text);for(d=n.length-1;0<=d;d--)n[d].dataset.tooltip=chrome.i18n.getMessage(n[d].dataset.message);b.querySelector("#customcss").setAttribute("placeholder",chrome.i18n.getMessage("custom_theme_instructions"));b.querySelector("#customscript").setAttribute("placeholder",chrome.i18n.getMessage("custom_script_instructions"))}else u=a.localecode,wa();d=b.querySelectorAll("nav a, aside a");d.forEach(c=>{c.addEventListener("focus",function(){this.parentNode.classList.add("focus")});
c.addEventListener("blur",function(){this.parentNode.classList.remove("focus")})});d[0].addEventListener("click",c=>{c.preventDefault();v.scrollTo(0,0)});d=b.querySelector("#locale");d.value=u;d.addEventListener("change",function(){u=this.value;wa()});d.addEventListener("focus",function(){this.parentNode.classList.add("focus")});d.addEventListener("blur",function(){this.parentNode.classList.remove("focus")});b.querySelectorAll("aside a").forEach(c=>{c.addEventListener("click",h=>{h.preventDefault();
var k=b.querySelector("fieldset."+h.target.dataset.target);v.scrollTop=0===v.scrollTop?1:v.scrollTop-1;v.addEventListener("scrollend",function Ka(){v.removeEventListener("scrollend",Ka);k.classList.add("highlighted");k.querySelector("input, textarea, select:not(.hidden), button").focus()});k.scrollIntoView()})});"#applyvideofilters #blackbars #blockhfrformats #blockwebmformats #boostvolume #cinemamode #cinemamodewideplayer #convertshorts #executescript #expanddescription #hidecardsendscreens #hidechat #hidecomments #hiderelated #hideshorts #newestcomments #reversemousewheeldirection #theatermode #wideplayer #wideplayerviewport".split(" ").forEach(c=>
{c=b.querySelector(c);c.checked=a[c.id];c.addEventListener("click",g)});b.querySelector("#keyboard-shortcuts-btn").addEventListener("click",()=>{chrome.runtime.sendMessage({request:"configure-keyboard-shortcuts"})});t=b.querySelectorAll('.player-control input[type="checkbox"]');for(d=0;d<t.length;d++)t[d].checked=-1<a.controls.indexOf(t[d].id)?!0:!1,t[d].addEventListener("click",Ia);n=b.querySelectorAll(".player-control .info");for(d=n.length-1;0<=d;d--)n[d].addEventListener("click",c=>{c.preventDefault()}),
n[d].addEventListener("mouseenter",c=>{c=c.target;var h=c.getBoundingClientRect();r.textContent=c.dataset.tooltip;r.style.setProperty("top","calc("+h.top+"px - .5rem)");r.style.setProperty("left",h.left+"px");r.classList.add("visible")}),n[d].addEventListener("mouseleave",()=>{r.classList.remove("visible")});var e=b.querySelectorAll('input[name="controlbaractive"]'),F=b.querySelector("#controlsvisible"),G=b.querySelector("#controlbarposition"),za=b.querySelector("#control-bar-centering"),H=b.querySelector("#controlbarcentered"),
Aa=b.querySelector("#control-bar-visibility"),I=b.querySelector("#controlbarautohide");for(d=0;d<e.length;d++)e[d].value===String(a.controlbar.active)&&(e[d].checked=!0),e[d].addEventListener("click",function(){"false"===this.value?(a.controlbar.active=!1,F.disabled=!1,G.disabled=!0,H.disabled=!0,I.disabled=!0):(a.controlbar.active=!0,F.disabled=!0,G.disabled=!1,H.disabled=!1,I.disabled=!1);chrome.storage.local.set({controlbar:a.controlbar})});F.checked=a.controlsvisible;F.disabled=a.controlbar.active;
F.addEventListener("click",g);G.value=a.controlbar.position;G.disabled=!a.controlbar.active;G.addEventListener("change",function(){za.classList["absolute"===this.value?"remove":"add"]("hidden");Aa.classList["fixed"===this.value?"remove":"add"]("hidden");a.controlbar.position=this.value;chrome.storage.local.set({controlbar:a.controlbar})});za.classList["absolute"===a.controlbar.position?"remove":"add"]("hidden");H.checked=a.controlbar.centered;H.disabled=!a.controlbar.active;H.addEventListener("click",
function(){a.controlbar.centered=this.checked;chrome.storage.local.set({controlbar:a.controlbar})});Aa.classList["fixed"===a.controlbar.position?"remove":"add"]("hidden");I.checked=a.controlbar.autohide;I.disabled=!a.controlbar.active;I.addEventListener("click",function(){a.controlbar.autohide=this.checked;chrome.storage.local.set({controlbar:a.controlbar})});d=b.querySelector("#backdropcolor");e=b.querySelector("#backdropopacity");var La=b.querySelector("#opacity"),Ma=b.querySelector("#cinemamode-backdrop"),
oa=()=>{var c=a.backdropcolor.replace("#",""),h=parseInt(c.substring(0,2),16),k=parseInt(c.substring(2,4),16);c=parseInt(c.substring(4,6),16);La.textContent=a.backdropopacity+"%";Ma.style.backgroundColor=`rgba(${h}, ${k}, ${c}, ${a.backdropopacity/100})`};d.value=a.backdropcolor;d.addEventListener("input",function(){a.backdropcolor=this.value;oa();chrome.storage.local.set({backdropcolor:this.value})});d.addEventListener("change",g);e.value=a.backdropopacity;e.addEventListener("input",function(){a.backdropopacity=
Number(this.value);oa();chrome.storage.local.set({backdropopacity:a.backdropopacity})});oa();var J=b.querySelector("#playback-speed"),K=b.querySelector("#custom-playback-speed");d=b.querySelector("#overridespeeds");var R=b.querySelector("#speedvariation");e=b.querySelector("#defaultvolume");var S=b.querySelector("#volume"),Ba=b.querySelector("#volume-preview"),q=b.querySelector("#volumemultiplier"),w=b.querySelector("#controlspeed"),T=b.querySelector("#controlspeedmousebutton"),L=b.querySelector("#controlvolume"),
U=b.querySelector("#controlvolumemousebutton"),V=b.querySelector("#volumevariation"),Ca=b.querySelector("#miniplayer"),W=b.querySelector("#miniplayersize"),X=b.querySelector("#miniplayerposition");J.value=a.overridespeeds?1:a.speed;J.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});K.value=a.overridespeeds?a.speed:1;K.addEventListener("change",function(){chrome.storage.local.set({speed:parseFloat(this.value)})});a.overridespeeds&&(J.classList.add("hidden"),
K.classList.remove("hidden"));d.checked=a.overridespeeds;d.addEventListener("click",function(){R.disabled=!this.checked;var c=b.querySelector("#playback-speed-label");c.classList.add("animated","blink");setTimeout(()=>{c.classList.remove("animated","blink")},2400);J.classList.toggle("hidden");K.classList.toggle("hidden");chrome.storage.local.set({overridespeeds:this.checked,speed:parseFloat(this.checked?K.value:J.value)})});R.value=a.speedvariation;R.disabled=!a.overridespeeds;R.addEventListener("change",
function(){chrome.storage.local.set({speedvariation:parseFloat(this.value)})});w.checked=a.controlspeed;w.addEventListener("click",function(){T.disabled=!this.checked;chrome.storage.local.set({controlspeed:this.checked})});T.checked=a.controlspeedmousebutton;T.disabled=!a.controlspeed;T.addEventListener("click",g);e.checked=a.defaultvolume;e.addEventListener("click",function(){S.disabled=!this.checked;chrome.storage.local.set({defaultvolume:this.checked})});S.value=a.volume;S.disabled=!a.defaultvolume;
S.addEventListener("input",function(){a.volume=Number(this.value);Ba.textContent=a.volume;chrome.storage.local.set({volume:a.volume})});Ba.textContent=a.volume;q.value=a.volumemultiplier;q.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});L.checked=a.controlvolume;L.addEventListener("click",function(){U.disabled=!this.checked;V.disabled=!this.checked;chrome.storage.local.set({controlvolume:this.checked})});U.checked=a.controlvolumemousebutton;U.disabled=
!a.controlvolume;U.addEventListener("click",g);V.value=a.volumevariation;V.disabled=!a.controlvolume;V.addEventListener("change",function(){chrome.storage.local.set({volumevariation:Number(this.value)})});q.value=a.volumemultiplier;q.addEventListener("change",function(){chrome.storage.local.set({volumemultiplier:Number(this.value)})});Ca.checked=a.miniplayer;Ca.addEventListener("click",function(){W.disabled=!this.checked;X.disabled=!this.checked;chrome.storage.local.set({miniplayer:this.checked})});
W.value=a.miniplayersize;W.disabled=!a.miniplayer;W.addEventListener("change",g);X.value=a.miniplayerposition;X.disabled=!a.miniplayer;X.addEventListener("change",g);d=b.querySelector("#blockautoplay");var Y=b.querySelector("#pauseforegroundtab"),Z=b.querySelector("#ignoreplaylists"),aa=b.querySelector("#stopvideos");d.checked=a.blockautoplay;d.addEventListener("click",function(){Y.disabled=!this.checked;Z.disabled=!this.checked;aa.disabled=!this.checked;chrome.storage.local.set({blockautoplay:this.checked})});
Y.checked=a.pauseforegroundtab;Y.disabled=!a.blockautoplay;Y.addEventListener("click",g);Z.checked=a.ignoreplaylists;Z.disabled=!a.blockautoplay;Z.addEventListener("click",g);aa.checked=a.stopvideos;aa.disabled=!a.blockautoplay;aa.addEventListener("click",g);d=b.querySelector("#pausevideos");var ba=b.querySelector("#ignorepopupplayer");d.checked=a.pausevideos;d.addEventListener("click",function(){ba.disabled=!this.checked;chrome.storage.local.set({pausevideos:this.checked})});ba.checked=a.ignorepopupplayer;
ba.disabled=!a.pausevideos;ba.addEventListener("click",g);d=b.querySelector("#disableautoplay");var Da=b.querySelector(".autoplay-toggle-button");d.checked=a.disableautoplay;Da.setAttribute("aria-checked",!a.disableautoplay);d.addEventListener("click",function(){Da.setAttribute("aria-checked",!this.checked);chrome.storage.local.set({disableautoplay:this.checked})});var pa=b.querySelector("#selectquality"),x=b.querySelector("#selectqualityfullscreenon"),M=b.querySelector("#selectqualityfullscreenoff"),
ca=["#qualityvideos","#qualityplaylists","#qualityembeds"],da=["#qualityvideosfullscreen","#qualityplaylistsfullscreen","#qualityembedsfullscreen"];pa.checked=a.selectquality;pa.addEventListener("click",function(){ca.forEach(c=>{b.querySelector(c).disabled=!pa.checked});x.disabled=!this.checked;this.checked?(ca.forEach(c=>{b.querySelector(c).disabled=!1}),x.disabled=!1,x.checked&&(da.forEach(c=>{b.querySelector(c).disabled=!1}),M.disabled=!1)):(ca.forEach(c=>{b.querySelector(c).disabled=!0}),x.disabled=
!0,da.forEach(c=>{b.querySelector(c).disabled=!0}),M.disabled=!0);chrome.storage.local.set({selectquality:this.checked})});ca.forEach(c=>{c=b.querySelector(c);c.value=a[c.id];c.disabled=!a.selectquality;c.addEventListener("change",g)});x.checked=a.selectqualityfullscreenon;x.addEventListener("click",function(){da.forEach(c=>{b.querySelector(c).disabled=!x.checked});M.disabled=!this.checked;chrome.storage.local.set({selectqualityfullscreenon:this.checked})});da.forEach(c=>{c=b.querySelector(c);c.value=
a[c.id];c.disabled=!a.selectqualityfullscreenon;c.addEventListener("change",g)});M.checked=a.selectqualityfullscreenoff;M.addEventListener("click",g);d=b.querySelector("#popuplayersize");d.value=a.popuplayersize;d.addEventListener("change",g);var qa=b.querySelector("#darktheme"),y=b.querySelectorAll('input[name="theme"]'),B=b.querySelector("#themevariant"),C=b.querySelector("#vendorthemevariant");e=b.querySelector("#customtheme");var ea=b.querySelector("#customcss");q=b.querySelector("#customcss-btn");
var fa=b.querySelector("#customcss-checkmark");d=y.length-1;qa.checked=a.darktheme;for(qa.addEventListener("click",function(){y.forEach(c=>{c.disabled=!qa.checked});this.checked?(B.disabled="enhanced-dark"===b.querySelector('input[name="theme"]:checked').value?!1:!0,C.disabled="youtube-deep-dark"===b.querySelector('input[name="theme"]:checked').value?!1:!0,O()):(B.disabled=!0,C.disabled=!0,m.forEach(c=>{c.disabled=!0}),P.disabled=!0);chrome.storage.local.set({darktheme:this.checked})});0<=d;d--)y[d].value===
a.theme&&(y[d].checked=!0),y[d].disabled=!a.darktheme,y[d].addEventListener("click",g),y[d].addEventListener("click",function(){B.disabled="enhanced-dark"===this.value?!1:!0;C.disabled="youtube-deep-dark"===this.value?!1:!0;O()});B.value=a.themevariant;B.disabled=a.darktheme?"enhanced-dark"===a.theme?!1:!0:!0;B.addEventListener("change",g);C.value=a.vendorthemevariant;C.disabled=a.darktheme?"youtube-deep-dark"===a.theme?!1:!0:!0;C.addEventListener("change",g);w=a.customcolors;for(d=m.length-1;0<=
d;d--)m[d].disabled=!a.darktheme,m[d].value=w[m[d].name],m[d].addEventListener("change",va);P.disabled=!a.darktheme;P.addEventListener("click",()=>{var c=D.customcolors;m.forEach(h=>{h.value=c[h.name]});va()});O();e.checked=a.customtheme;e.addEventListener("click",function(){chrome.storage.local.set({customtheme:this.checked})});ea.disabled=!a.customtheme;ea.value=a.customcss;ea.addEventListener("focus",()=>{fa.classList.remove("show")});q.disabled=!a.customtheme;q.addEventListener("click",()=>{fa.classList.add("show");
chrome.storage.local.set({customcss:ea.value})});fa.addEventListener("animationend",c=>{"checkmark-scale"===c.animationName&&setTimeout(()=>{fa.classList.remove("show")},1200)});var ra=b.querySelector("#customscript");d=b.querySelector("#customscript-btn");var ha=b.querySelector("#customscript-checkmark");ra.value=a.customscript;ra.addEventListener("focus",()=>{ha.classList.remove("show")});d.addEventListener("click",()=>{ha.classList.add("show");chrome.storage.local.set({customscript:ra.value})});
ha.addEventListener("animationend",c=>{"checkmark-scale"===c.animationName&&setTimeout(()=>{ha.classList.remove("show")},1200)});f=a.griditemsperrow;d=b.querySelector("#videos-per-row");var ia=b.querySelector("#videos-per-row-count");e=b.querySelector("#channel-videos-per-row");var ja=b.querySelector("#channel-videos-per-row-count");q=b.querySelector("#shorts-per-row");var ka=b.querySelector("#shorts-per-row-count");w=b.querySelector("#channel-shorts-per-row");var la=b.querySelector("#channel-shorts-per-row-count");
L=b.querySelector("#posts-per-row");var ma=b.querySelector("#posts-per-row-count");d.checked=f.videos.apply;d.addEventListener("click",function(){f.videos.apply=this.checked;ia.disabled=!this.checked;p()});ia.value=f.videos.count;ia.disabled=!f.videos.apply;ia.addEventListener("change",function(){f.videos.count=parseFloat(this.value);p()});e.checked=f.channel.videos.apply;e.addEventListener("click",function(){f.channel.videos.apply=this.checked;ja.disabled=!this.checked;p()});ja.value=f.channel.videos.count;
ja.disabled=!f.channel.videos.apply;ja.addEventListener("change",function(){f.channel.videos.count=parseFloat(this.value);p()});q.checked=f.shorts.apply;q.addEventListener("click",function(){f.shorts.apply=this.checked;ka.disabled=!this.checked;p()});ka.value=f.shorts.count;ka.disabled=!f.shorts.apply;ka.addEventListener("change",function(){f.shorts.count=parseFloat(this.value);p()});w.checked=f.channel.shorts.apply;w.addEventListener("click",function(){f.channel.shorts.apply=this.checked;la.disabled=
!this.checked;p()});la.value=f.channel.shorts.count;la.disabled=!f.channel.shorts.apply;la.addEventListener("change",function(){f.channel.shorts.count=parseFloat(this.value);p()});L.checked=f.posts.apply;L.addEventListener("click",function(){f.posts.apply=this.checked;ma.disabled=!this.checked;p()});ma.value=f.posts.count;ma.disabled=!f.posts.apply;ma.addEventListener("change",function(){f.posts.count=parseFloat(this.value);p()});d=b.querySelector("#export-modal-btn");e=b.querySelector("#import-modal-btn");
var l=b.querySelector("#backup-modal"),Ea=l.querySelector(".close-modal"),Fa=l.querySelector("#export-modal-content"),Ga=l.querySelector("#export-textarea"),Ha=l.querySelector("#import-modal-content"),sa=l.querySelector("#import-error"),na=l.querySelector("#import-textarea"),ta=l.querySelector("#import-btn"),ua=l.querySelector("#copy-to-clipboard-btn"),N=l.querySelector("#copy-to-clipboard-checkmark");d.addEventListener("click",()=>{Fa.classList.remove("hidden");ua.classList.remove("hidden");N.classList.remove("hidden");
xa(l);chrome.storage.local.get(null,c=>{var h={};h.version=chrome.runtime.getManifest().version;h.settings={};Object.keys(D).forEach(k=>{h.settings[k]=void 0===c[k]?D[k]:c[k]});Ga.value=JSON.stringify(h,null,2)})});e.addEventListener("click",()=>{Ha.classList.remove("hidden");ta.classList.remove("hidden");xa(l)});Ea.addEventListener("click",()=>{Ja(l);setTimeout(()=>{Fa.classList.add("hidden");Ha.classList.add("hidden");sa.classList.add("hidden");ta.classList.add("hidden");ua.classList.add("hidden");
N.classList.add("hidden");na.value=""},600)});ua.addEventListener("click",async()=>{await navigator.clipboard.writeText(Ga.value);N.classList.add("show")});N.addEventListener("animationend",c=>{"checkmark-scale"===c.animationName&&setTimeout(()=>{N.classList.remove("show")},1200)});ta.addEventListener("click",async()=>{var c=na.value.trim();if(""!==c){try{c=JSON.parse(c)}catch(k){sa.classList.remove("hidden");na.value=k;return}if("object"===typeof c.settings&&c.version&&(/^3\.\d+\.\d+/.test(c.version)||
/^2\.0\.1(0[2-9]|[1-2][0-9])/.test(c.version))){Array.isArray(c.settings.controls)&&(c.settings.controls=c.settings.controls.filter(z=>"whitelist"!==z&&"not-interested"!==z));c.settings.backgroundcolor&&(c.settings.backdropcolor=c.settings.backgroundcolor,delete c.settings.backgroundcolor);c.settings.backgroundopacity&&(c.settings.backdropopacity=c.settings.backgroundopacity,delete c.settings.backgroundopacity);c.settings.customcssrules&&(c.settings.customcss=c.settings.customcssrules,delete c.settings.customcssrules);
c.settings.miniplayersize&&(c.settings.miniplayersize=c.settings.miniplayersize.replace("_",""));c.settings.miniplayerposition&&(c.settings.miniplayerposition=c.settings.miniplayerposition.replace("_",""));"default-light"===c.settings.theme&&(c.settings.theme="default-dark");let k;if(null==(k=c.settings.themevariant)?0:k.includes("youtube-deep-dark"))c.settings.vendorthemevariant=c.settings.themevariant.replace("-youtube-light",""),delete c.settings.themevariant;var h={};Object.keys(c.settings).forEach(z=>
{typeof D[z]===typeof c.settings[z]&&(h[z]=c.settings[z])});await chrome.storage.local.clear();chrome.storage.local.set(h,()=>{v.scrollTo(0,0);b.location.reload()})}else sa.classList.remove("hidden"),!c.version||/^3\.\d+\.\d+/.test(c.version)&&/^2\.0\.1(0[2-9]|[1-2][0-9])/.test(c.version)||(na.value="Outdated backup...")}});b.addEventListener("keydown",c=>{"Escape"===c.key&&"block"===l.style.display&&Ea.click()})});window.addEventListener("resize",ya);ya();b.addEventListener("transitionend",a=>{a=
a.target;a===r?(a=r.getBoundingClientRect(),0>=a.left?r.style.setProperty("left","calc("+a.width/2+"px + .5rem)"):a.right>b.documentElement.clientWidth&&r.style.setProperty("left","calc("+(b.documentElement.clientWidth-a.width/2)+"px - .5rem)")):"FIELDSET"===a.nodeName&&a.classList.remove("highlighted")})})(document,config);