# config/regreet.toml
# OJO: sin [appearance] para que Stylix gobierne el tema/iconos/cursor/fuentes.

[background]
image = "/etc/greetd/wallpapers/login.jpg"

[clock]
enabled = true
format = "%H:%M"

[greeting]
text = "WillWitcherOS"
